name: Label when approved
on:
  pull_request_review:
    types:
      - submitted

permissions:
  pull-requests: write

jobs:
  label-when-approved:
    name: "Label when approved"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Label when approved by commiters
        uses: TobKed/label-when-approved-action@v1.2
        with:
          token: ${{ secrets.ACCESS_TOKEN_MASTER }}
          label: '🎉STATUS: approved'
          require_committers_approval: 'false'
          comment: 'PR is approved by collaborator'
          pullRequestNumber: ${{ github.event.pull_request.number }}
